name: Hello

on:
  push:
    branches:
      - main

env:
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
  ALGOLIA_WRITE_API_KEY: ${{ secrets.ALGOLIA_WRITE_API_KEY }}


jobs:
  foo:
    name: foo
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: prepare envs
        run: |
          echo ALGOLIA_APP_ID=${ALGOLIA_APP_ID} >> .dev.vars
          echo ALGOLIA_SEARCH_API_KEY=${ALGOLIA_SEARCH_API_KEY} >> .dev.vars
          echo ALGOLIA_WRITE_API_KEY=${ALGOLIA_WRITE_API_KEY} >> .dev.vars
